server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/emall?characterEncoding=utf-8
    username: root
    password: 1234
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: -1
    # 连接池中的最大空闲连接
    pool.max-idle: 8
    # 连接池中的最小空闲连接
    pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0


## Mybatis 配置
mybatis:
  typeAliasesPackage: com.lujiahao.sso.domain.pojo
  mapperLocations: classpath:mapper/*.xml
